import { defineConfig } from "oxlint"

export default defineConfig({
  plugins: ["typescript", "unicorn", "oxc"],
  categories: {
    correctness: "error",
    suspicious: "warn",
    perf: "warn",
    style: "warn",
    restriction: "error",
  },
  rules: {
    "no-shadow-restricted-names": "off",
    "prefer-template": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-empty-interface": "off",
    "prefer-ternary": "off",
    "sort-keys": "off",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-member-accessibility": "off",
    "typescript/explicit-module-boundary-types": "off",
    "no-use-before-define": "off",
    "no-dynamic-delete": "off",
    "id-length": "off",
    "new-cap": "off",
    "no-shadow": "off",
    "no-ternary": "off",
    "func-style": ["error", "declaration"],
    "typescript/prefer-function-type": "off",
    "typescript/consistent-indexed-object-style": "off",
    "no-undefined": "off",
    "filename-case": "off",
    "no-magic-numbers": "off",
    "max-statements": "off",
    "no-plusplus": "off",
    "no-array-for-each": "off",
    "sort-imports": "off",
    "no-optional-chaining": "off",
    "default-case": "off",
    "prefer-for-of": "off",
    "switch-case-braces": "off",
    "require-module-specifiers": "off",
    "typescript/no-namespace": "off",
  },
  ignorePatterns: ["**/*.gen.ts"],
})
