export const HTTP = {
  method: {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    PATCH: "PATCH",
    DELETE: "DELETE",
    HEAD: "HEAD",
    OPTIONS: "OPTIONS",
  },
  status: {
    NoContent: 204,
    MovedPermanently: 301,
    Forbidden: 403,
    PayloadTooLarge: 413,
    UnsupportedMediaType: 415,
    TooManyRequests: 429,
  },
  statusText: {
    Forbidden: "Forbidden",
    PayloadTooLarge: "Payload Too Large",
    UnsupportedMediaType: "Unsupported Media Type",
    TooManyRequests: "Too Many Requests",
  },
  header: {
    Accept: "Accept",
    Authorization: "Authorization",
    CacheControl: "Cache-Control",
    ContentLength: "Content-Length",
    ContentType: "Content-Type",
    Cookie: "Cookie",
    Origin: "Origin",
    Referrer: "Referer",
    SetCookie: "Set-Cookie",
    Vary: "Vary",
    XContentTypeOptions: "X-Content-Type-Options",
    XForwardedFor: "X-Forwarded-For",
    XFrameOptions: "X-Frame-Options",
    XRequestId: "X-Request-Id",
    XCsrfToken: "X-CSRF-Token",
    StrictTransportSecurity: "Strict-Transport-Security",
    ReferrerPolicy: "Referrer-Policy",
    AccessControlAllowOrigin: "Access-Control-Allow-Origin",
    AccessControlAllowMethods: "Access-Control-Allow-Methods",
    AccessControlAllowHeaders: "Access-Control-Allow-Headers",
    AccessControlExposeHeaders: "Access-Control-Expose-Headers",
    AccessControlAllowCredentials: "Access-Control-Allow-Credentials",
    AccessControlMaxAge: "Access-Control-Max-Age",
    AccessControlRequestMethod: "Access-Control-Request-Method",
    AccessControlRequestHeaders: "Access-Control-Request-Headers",
    ContentSecurityPolicy: "Content-Security-Policy",
    ContentSecurityPolicyReportOnly: "Content-Security-Policy-Report-Only",
    CFConnectingIP: "CF-Connecting-IP",
    XRateLimitLimit: "X-RateLimit-Limit",
    XRateLimitRemaining: "X-RateLimit-Remaining",
    XRateLimitReset: "X-RateLimit-Reset",
  },
  contentType: {
    json: "application/json",
    urlencoded: "application/x-www-form-urlencoded",
    formData: "multipart/form-data",
    text: "text/plain",
    html: "text/html",
    octetStream: "application/octet-stream",
  },
  referrerPolicy: {
    noReferrer: "no-referrer",
    noReferrerWhenDowngrade: "no-referrer-when-downgrade",
    origin: "origin",
    originWhenCrossOrigin: "origin-when-cross-origin",
    sameOrigin: "same-origin",
    strictOrigin: "strict-origin",
    strictOriginWhenCrossOrigin: "strict-origin-when-cross-origin",
    unsafeUrl: "unsafe-url",
  },
  frameOption: {
    deny: "DENY",
    sameOrigin: "SAMEORIGIN",
  },
  contentTypeOptions: {
    nosniff: "nosniff",
  },
} as const
